name: Reproduire
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  reproduire:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: Hebilicious/reproduire@a4b274773e3d6e8bef547385710473af11f5ec5d # v0.0.9-mp
        with:
          label: 'status: need more repro codes or info' # Optional, will default to this value.
