name: Typos
on:
  pull_request:
    branches-ignore:
      - gh-pages
      - releases/**
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Spell check
        uses: crate-ci/typos@85f62a8a84f939ae994ab3763f01a0296d61a7ee # v1.36.2
